name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Test SSH connection with ed25519
        continue-on-error: true
        run: |
          ssh -v -o StrictHostKeyChecking=no -p 22 -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH ed25519 successful'"

      - name: Test SSH connection with RSA
        continue-on-error: true
        run: |
          ssh -v -o StrictHostKeyChecking=no -p 22 -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo 'SSH RSA successful'"

      - name: Deploy project to VPS
        run: |
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 -i ~/.ssh/id_ed25519" \
            . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/docker/arcane || \
          rsync -az --delete \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 22 -i ~/.ssh/id_rsa" \
            . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/docker/arcane

      - name: Create .env on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" > /home/docker/arcane/.env' || \
          ssh -o StrictHostKeyChecking=no -p 22 -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" > /home/docker/arcane/.env'

      - name: Restart Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -p 22 -i ~/.ssh/id_ed25519 ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd /home/docker/arcane && export SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" && sudo -E docker-compose down && sudo -E docker-compose up --build -d' || \
          ssh -o StrictHostKeyChecking=no -p 22 -i ~/.ssh/id_rsa ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'cd /home/docker/arcane && export SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" && sudo -E docker-compose down && sudo -E docker-compose up --build -d'